auto: true

rouge: true
paginate: 8
permalink: /:title

title: SeikiRJ's Blog
description: Notes on software engineering, learning experiments, and side projects by SeikiRJ.
url: https://seikirj.github.io
feed: /atom.xml
author: SeikiRJ
author_info: <a href="https://seikirj.github.io">SeikiRJ</a>
lang: en
social_image: /favicon.ico
